
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace GTC {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorPicker colorPicker;
        
        private void InitializeComponent() {
            this.colorPicker = new Terminal.Gui.ColorPicker();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.colorPicker.Width = 32;
            this.colorPicker.Height = 5;
            this.colorPicker.X = 0;
            this.colorPicker.Y = 0;
            this.colorPicker.Visible = true;
            this.colorPicker.Data = "colorPicker";
            this.colorPicker.Text = "Hello!";
            this.colorPicker.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.colorPicker);
        }
    }
}
